
services:
  
  app:
    build: .
    container_name: portal-empleado-app
    ports:
      - "3000:3000" # Mapea el puerto de tu app
    
    
    environment:
      # --- Las variables de .env ---
      DB_NAME: ${DB_NAME}         # 'vacation_portal'
      USER_DB: ${USER_DB}         # 'root'
      PASSWORD_DB: ${PASSWORD_DB} 
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES: ${JWT_EXPIRES}
      CORS_ORIGIN: ${CORS_ORIGIN}
      DB_DIALECT: ${DB_DIALECT}   # 'mysql'
      
      
    
    
      HOST: host.docker.internal 

      PORT: 3000
      NODE_ENV: development

