name: üöÄ Build y Publicar Imagen Docker

on:
  push:
    branches:
      - main
      - develop
      - feature/dockerizacion # mi rama
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name:  Descargar el c√≥digo
        uses: actions/checkout@v4

      - name:  Poner el nombre del repo en min√∫sculas
        id: string
        run: echo "repository_lowercase=${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT

    
      - name:  Crear etiqueta v√°lida para Docker
        id: tag_name
        run: |
          CLEAN_TAG=${GITHUB_REF_NAME//\//-}
          echo "TAG=$CLEAN_TAG" >> $GITHUB_OUTPUT

      - name:  Iniciar sesi√≥n en el Almac√©n (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name:  Construir y Guardar la imagen
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ steps.string.outputs.repository_lowercase }}:${{ steps.tag_name.outputs.TAG }}
