name: üöÄ Build y Publicar Imagen Docker

on:
  push:
    branches:
      - main       # Cuando subas a 'main'
      - develop    # Cuando subas a 'develop'
      - feature/dockerizacion # mi rama

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    

    permissions:
      contents: read
      packages: write 
    steps:
      
      - name: ‚¨áÔ∏è Descargar el c√≥digo
        uses: actions/checkout@v4

     
      - name: üî° Poner el nombre en min√∫sculas
        id: string
        run: echo "repository_lowercase=${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT

    
      - name: üîê Iniciar sesi√≥n en el Almac√©n (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          
          password: ${{ secrets.GITHUB_TOKEN }} 

     
      - name: üì¶ Construir y Guardar la imagen
        uses: docker/build-push-action@v5
        with:
          context: .       # Usa el Dockerfile de la ra√≠z
          push: true       # S√≠, gu√°rdala en el almac√©n
          
          #  La "Etiqueta" de la imagen
          # (ej: ghcr.io/g2-finalproject/portal-empleado-server:develop)
          tags: ghcr.io/${{ steps.string.outputs.repository_lowercase }}:${{ github.ref_name }}